### ISSUE TITLE
Add whisper transcriber

### ISSUE THREAD

**Issue by MatthiasReumann** [TUM-Dev/TUM-Live-Voice-Service#13]
## Description
Add support for OpenAI's [whisper](https://github.com/openai/whisper) transcriber. 

## Tasks

- [ ] Since the vosk-transcriber is already implemented, the transcriber should be configurable.
- [ ] When specified, whisper language models should be downloaded and saved automatically at the beginning of execution.
- [ ] Whisper can detect languages automatically. The current request has an attribute called `language`. Find a solution and figure out how to deal with silences at the beginning of the video.
- [ ] Make sure to update the `README.md`.
